version: '3.3'
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: ["./wait-for-it.sh" , "db:5432" , "--strict" , "--timeout=300" , "--","./docker_endwait.sh"]
        volumes:
            - .:/code
        ports: 
            - "8000:8000"
        depends_on:
            - db
        links:
            - db