# Generated by Django 3.1.6 on 2021-05-02 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20210501_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
