# Generated by Django 3.1.6 on 2021-05-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210502_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products_pics'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerproduct_created', to='offers.product'),
        ),
    ]
