# Generated by Django 3.1.6 on 2021-05-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210503_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image',
            new_name='image_offer',
        ),
    ]
