# Generated by Django 3.1.6 on 2021-05-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20210503_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image_offer',
            new_name='image',
        ),
    ]
