# Generated by Django 3.1.6 on 2021-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210503_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='url_offer',
            field=models.URLField(default='https://www.chollometro.com/', max_length=250),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products_pics'),
        ),
    ]
