# Generated by Django 3.1.6 on 2021-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20210506_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pictures_offers'),
        ),
    ]
