# Generated by Django 3.1.6 on 2021-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20210506_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='offers/'),
        ),
    ]
