# Generated by Django 3.1.6 on 2021-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20210506_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
