# Generated by Django 3.1.6 on 2021-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_offer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, help_text='*Add address in case the offer is in a local site', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='url_offer',
            field=models.URLField(default='', help_text='*In case the offer is local put the shop website URL', max_length=250),
        ),
    ]
