# Generated by Django 3.1.6 on 2021-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20210512_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, help_text='*Add address in case the offer is in a local site', max_length=1000),
        ),
    ]
